sudo: required
services:
- docker
language: minimal
addon:
  apt:
    update: true
    packages:
    - bc
    - jq
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- mkdir -p ~/.local/lib && mkdir -p ~/.local/bin
- git clone https://$PV_OATH_TOKEN@github.com/polyverse-security/pv ~/.local/lib/pv
- ln -s ~/.local/lib/pv/pv ~/.local/bin/pv
script:
- "./build.sh   || travis_terminate 1"
- "./test.sh    || travis_terminate 1"
- "./publish.sh || travis_terminate 1"
env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - secure: EQFLNcgaOM7HQKVwfAmdk4qruMsXPsYOT3fRf3v0wSoaQmtixml6w6HIEoUiOOkMC59bG+eayVCskfixNoyLUVO5Ug3ZIRDX1Yt0EAb2HAgYydBghv5SJcJOHPlQOLdpSeEsgeoJQ9V3gD8ZVulGpJ38TOO3Ewnr4IWysjmJrJ/aoaCGmMgR8FMJhrzl/UagilRZUAeqBEK3pjulPlhasEqc1/s+jPhy3MZRRF7kF2mIhYLY+Zrq5Hq7QfNURJKC0pSFeNNCcerbEZAbG+x3//b3uUKfqQJCYMREuiOsWZ6B/MXRV6u0GAkUJ0jC9RtnTDKdShNg0ixBHQSq8ofWPkJm1ub3s11GPmF4ri8Tv3zjazej1BlJ1S4/h73OdsC0g0q4UOqZQN84riE1q/hZVzbNW7yGTd8ZxveZpnVvl8NMbPP/4WU03T4vQL0ITO30fkNYjsCVFcQqvVrtXUhcZTQqgp65LfH8bVNjzD0vlIBdwidnZ6ABVlxK4rO0tE5jbsxHuXOaaHddaHqCJRqs0WduB6Co4I9TQoEPtnCv5BJy9PZbUVGSSxBS3erRF4v8gIvlOEhZJ9dqC/dGhqPdYQJTPFZ+XUSQiu7tCAqm3PbBKzA/YZKF9zVcUQF/0LVRYjtJmFokqemdUCm0Iu9f2cVowEe1Aa8WMfv014QCfzI=
  - secure: futBp3KJHY+30x8808xxqjxs5pcB44Wps47wLB/hnpn6rhD1QVbBz98BA2idSa6SSXoKvtUKWe6Wz3TVvrd7UtJ5FbhtgWE9zwMcet8zPLHCDv25iX0xT9got0+XaIwMquOnqwyJ3u5qBdOgFM/HZ/t7APf/4N8/tBVYz+9axNX6wi7Jfd3BhckoGabnjuVpcQ1FL4cJuRRZKeBtJjyKs7GdvswhWlnW4WK+7+KRO5HfJMkj2+pZ/5n+8qkliCyXCSgLu/xeMviONfSd6OcwcmdTQ24i4IcfpAyTStFNRmIKzMt8n9ykjUJNqCH8MqW/FDGdTuZPRNtvI6wKE26tZSWfbGygUQ9s+clTMqTeHJSZpcnVAIjviGyey0gLQeqQg9sTy2H67NCiS3P9alsnwd4gH+6XJC3+AfbY7/lEs1nAQqzfua1KWyDXSHXiUdpMTEPV8Ust4WR8pkzl8GhShe2Z/uiG+P1JIXnh0/AMbOTZrx2v4fUY846tTbHI+XUHS6DqWUq94qg1WvrSsQzZBXMLJX3RY+25I/xT9ehM9vGHO649+iBm5c1j02vyWlfsbGGG4umdh5Jh1y7jegzitEBdFd3so1H/L6y1lyvXZPlFhOtHnxi1lvz099kvvGhYcLtOTU4k4AsVIkLz24UDofGXYuAo4h38SjpLpn6cXlM=
  - secure: T37jTwh2SwTaAQBao4AJzsxrFcYGqNvqJPuQrI0ikb4Oa/fIQxCLG/abFg7rb51CN7F6zoN7lx6insDlTBEuWObGKJA6N7ffjguuEHNM/pfugZLqGW18HzMeUXSHFU2nDOPM5Q8MhYFwwMeORun7im2bIQQUn3MNs9tMYMr0AjzERbwYLKfq2L2up3B0nIlQja9dth6jbJjK9ZvGBaTfDFar7gHiTePqA7ZuMfO41b9j/A5CmsXsdCGLVpfgWbP690PUUAjJyyklSktVXL3SA6i8E6DvDUKBZlj0Ll6bjHe1qs8bN7rsdPs/zb3U1bYKzTpd1pwulPPgYg0elCEmiCXB/3x1DGj8uaF2Ii4fxgGxV0kDlf0rXc5VgnZJN7nrgCSQtru/5HZkoIonr4OHqC7nyD7FJ5MkJryhl4+swiiyKqO/fDGxdzwxzq4oBIvqM8FmlovHIMAAjhPY9Cb7cGiU87BEeDTenk3S/LQVyuslEv8BUoTYe5hIJsq7l0b3Aa2t6bwry0ANFo5jhnVLPW+VS4MQ5w03hRelQsbqFWfgWDw4SvH5yt5NZThYdwXAZOVDpCNvbabA07OC/pGubXdE4oV/Gswa7RfzpX/iwirw1KhC1yxqiZOCHqPU6WalCtmNz6y88LLytwaaWZcXNLyw2gkY8KFZZZgkdwVzzUY=
notifications:
  slack:
    secure: "lneSHPnIpBryK2mrB8fS7Z7U33bEWpr1i7bH6F/7fKBCaUZZkhtiu27pOjQOJN+d31PSmjzjSzRorZIQVmuD86OxT/PuC+B2MODArEeN069dx6m6r/EgpcaOGujDYxXFOe2KzE779CS4EhlDTpQ4AZMEBjJVaGR5DEa2z1kKsjtvLLbre8PH6eyZBfiLbO127VVO08K5d3y2fehL0Mj/VUScXasMbeWIUBDbg69gEbVqSpE6PwbjRM2HM4z3EBPtOqZv1YOfNEPwF22z8SshtexgukOztfSc4o6P6ZHvayTOKBf6Xp71Jmgv0JcqCqyzM9cfIS1JfcHl7v2hJlLY870a35LhdUA7Sem8gUsmAu4HVUGW9OWOVckiN/d8ErhKzWgaSmW6ZFemAmiAsS8DXYagxgwKU4htSgvAh5r2BcrH7r3n4Y8jlH4ea0vrFcJM63+c152e7UcbGEuIDRmdzsANiGaCcEe5idENoWOfKeoLXUxT1aF4teqr7XSTC/mQQck5bRIDot2QNFwYorI1gr2XnWfoZOm+pDv/0r5/6ftKEvp+KKIcRVrEc1TXd2/SwTUPNQxxMFB/h28lKclZXLqhZ6A9vGPEQkRTdB7MpjXMtXmC0nmOKqLyjdJaHtxl6xRS2ql5pCHnnDgnZfp/VgHhlWl3F1MZ3tKqo0zlm2Y="